### ISSUE TITLE
Unlock in TeamAllocation.sol

### ISSUE THREAD

**Issue by Phistr90** [twentythirty/PillarToken#1]
I guess that function does nothing (except burning some gas) if I understand transfer from BasicToken correctly. 
https://github.com/twentythirty/PillarToken/blob/master/contracts/TeamAllocation.sol#L57

It sends from msg.sender the value toTransfer to msg.sender, doesnt it?

I assume it should be used transferFrom instead.

**Comment by ch4r10t33r** [comment]
TeamAllocation is basically multisig wallet that will hold the tokens allocated to the team members for a period of 9 months. Post which the individual tokens will be transferred to the team members. 

As the percentage of team allocation is yet to be finalized, this code isn't complete/is WIP. But yes, we will be using transferFrom of the PillarToken to do the actual transfers.
